# Generated by Django 4.1.3 on 2022-11-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_temp_id_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
