# Generated by Django 4.1.3 on 2022-11-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
